# Generated by Django 4.2.16 on 2024-11-17 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_gym', models.ForeignKey(blank=True, help_text='Select the default gym for this installation. This will assign all new registered users to this gym and update all existing users without a gym.', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.gym', verbose_name='Default gym')),
            ],
        ),
    ]
